#!/usr/bin/env bash

# Check for bucket name
if [ -z "$1" ]; then
    echo "Bucket name is required"
    exit 1
fi

BUCKET_NAME=$1

# Delete bucket
aws s3api delete-bucket \
    --bucket "$BUCKET_NAME" \
    --output text

if [ $? -eq 0 ]; then
    echo "Bucket $BUCKET_NAME deleted successfully."
else
    echo "Failed to delete bucket $BUCKET_NAME"
fi